language: php

php:
  - 5.6
  - 7.3
  - 7.4snapshot

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: CHECKS=1 DEFAULT=0

  fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $DEFAULT == 1 ]]; then composer phpstan-setup && composer phpstan ; fi

  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

notifications:
  email: false
