<?php
/**
 * Created by PhpStorm.
 * User: ewb
 * Date: 6/17/17
 * Time: 8:43 AM
 */

namespace PSR2R\Tests\Classes;

class BraceOnSameLineSniff
{

}

class BraceOnSameLineSniffOk {

}
trait BraceOnSameLineSniffT
{

}

trait BraceOnSameLineSniffOkT {

}
interface BraceOnSameLineSniffI
{

}

interface BraceOnSameLineSniffOkI {

}

function braceFunction1()
{}

function braceFunction2()
{

}

function braceFunctionOk() {

}
