<?php
/**
 * Created by PhpStorm.
 * User: ewb
 * Date: 6/17/17
 * Time: 12:51 PM
 */

namespace PSR2R\Tests\Commenting;

class DocBlockPipeSpacingUnitTest {
	/**
	 * @param array|null $var
	 */
	public function one(array $var = null) {

	}
	/**
	 * @param array |null $var
	 */
	public function two(array $var = null) {

	}
	/**
	 * @param array| null $var
	 */
	public function three(array $var = null) {

	}
	/**
	 * @param array | null $var
	 */
	public function four(array $var = null) {

	}
}
