<?php
/**
 * Created by PhpStorm.
 * User: ewb
 * Date: 6/17/17
 * Time: 12:51 PM
 */

namespace PSR2R\Tests\Commenting;

use PSR2R\Base\AbstractBase;

/**
 * One
 */
function one() {
}
class DocBlockReturnTagUnitTestInc {
	/**
	 * DocBlockReturnTagUnitTestInc constructor
	 * @return $this
	 */
	public function __construct() {

	}

	/**
	 * @return void
	 */
	public function __destruct() {

	}

	/**
	 * Two
	 */
	public function two() {

	}
	/**
	 * @return void
	 */
	public function three() {

	}
}
